# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20161222_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='extension',
            field=models.CharField(default='txt', max_length=5),
            preserve_default=False,
        ),
    ]
